"""rename address

Revision ID: 1e31f101a32a
Revises: dba10408cca2
Create Date: 2024-07-28 13:54:22.244544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e31f101a32a'
down_revision = 'dba10408cca2'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###  we only need to alter column no need to add and drop columns.
#     op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
#     op.drop_column('departments', 'address')
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
#     op.drop_column('departments', 'location')
#     # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
