"""rename department

Revision ID: 2eeecf71a8d6
Revises: 1029eebe8428
Create Date: 2024-07-28 13:43:50.675380

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '2eeecf71a8d6'
down_revision = '1029eebe8428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'departmentss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departmentss', 'departments')
    # ### end Alembic commands ###
